# Generated by Django 5.2 on 2025-05-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220416_0113'),
        ('posts', '0003_alter_follow_following'),
    ]

    operations = [
    ]
